kind = "api"
previewPath = "/"
title = "Volume Profile Dashboard"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Start application"
paths = ["/"]

[services.development]
run = "cd /home/runner/workspace && streamlit run app.py --server.port 8080"

[services.production]
run = "bash serve.sh"
